[package]
name = "bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nes = { path = "../nes", default-features = false }
dhat = "0.3.2"

[profile.release]
debug = 1